/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/K5Mnyqrr857
 */
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Chatinterface() {
  return (
    <div className="flex flex-col h-screen">
      <header className="sticky top-0 z-10 bg-white border-b">
        <div className="container px-4">
          <div className="h-14 flex items-center">
            <h1 className="text-lg font-semibold">Chat with GPT</h1>
          </div>
        </div>
      </header>
      <div className="flex-1 bg-gray-100 border-t border-gray-200">
        <div className="container px-4 py-6 flex flex-col gap-4">
          <div className="grid gap-2">
            <div className="rounded-xl bg-gray-50 border p-4 flex flex-col gap-2">
              <div className="text-sm text-gray-500">2:30 PM</div>
              <div className="text-base leading-7">Hi there! How can I help you today?</div>
            </div>
            <div className="rounded-xl bg-gray-50 border p-4 flex flex-col gap-2">
              <div className="text-sm text-gray-500">2:31 PM</div>
              <div className="text-base leading-7">
                I'm having trouble with my internet connection. It keeps dropping out, and I'm not sure what to do.
              </div>
            </div>
            <div className="rounded-xl bg-gray-50 border p-4 flex flex-col gap-2">
              <div className="text-sm text-gray-500">2:32 PM</div>
              <div className="text-base leading-7">
                I'm sorry to hear that. Let me see if I can help. Have you tried restarting your router?
              </div>
            </div>
            <div className="rounded-xl bg-gray-50 border p-4 flex flex-col gap-2">
              <div className="text-sm text-gray-500">2:33 PM</div>
              <div className="text-base leading-7">Yes, I've tried that, but it didn't seem to make a difference.</div>
            </div>
          </div>
          <div className="flex gap-2">
            <Input className="flex-1" placeholder="Type your message here." />
            <Button>Send</Button>
          </div>
        </div>
      </div>
    </div>
  )
}
